services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

        bind:
            $commandBus: '@messenger.bus.commands'
            $eventBus: '@messenger.bus.events'

    Xm\SymfonyBundle\Messenger\CommandEnricherMiddleware: ~
    Xm\SymfonyBundle\Messenger\CommandRecorderMiddleware: ~
    Xm\SymfonyBundle\Messenger\FailureCatcherMiddleware: ~

    Xm\SymfonyBundle\DataProvider\IssuerProvider: ~

    Xm\SymfonyBundle\Projection\User\UserFinder: ~
    Xm\SymfonyBundle\Projection\User\UserTokenFinder: ~

    Xm\SymfonyBundle\Infrastructure\Service\ChecksUniqueUsersEmailFromReadModel: ~
    Xm\SymfonyBundle\Model\User\Service\ChecksUniqueUsersEmail: '@Xm\SymfonyBundle\Infrastructure\Service\ChecksUniqueUsersEmailFromReadModel'

    Xm\SymfonyBundle\Security\TokenGenerator: ~
    Xm\SymfonyBundle\Security\TokenGeneratorInterface: '@Xm\SymfonyBundle\Security\TokenGenerator'

    Xm\SymfonyBundle\Security\PasswordEncoder: ~
    Xm\SymfonyBundle\Security\UserChecker: ~
    Xm\SymfonyBundle\Security\TokenValidator: ~

    Xm\SymfonyBundle\EventSourcing\Aggregate\RepositoryFactory: ~

    Xm\SymfonyBundle\EventSourcing\Aggregate\AggregateRepository:
        abstract: true
        factory: 'Xm\SymfonyBundle\EventSourcing\Aggregate\RepositoryFactory:create'

    Xm\SymfonyBundle\EventSourcing\Aggregate\AggregateTranslator: ~

    Xm\SymfonyBundle\EventStore\MetadataIssuedByEnricher:
        tags: [ 'prooph_event_store.metadata_enricher' ]

    Xm\SymfonyBundle\EventStore\EventStoreMessengerPlugin:
        tags: [ 'prooph_event_store.plugin' ]

    Xm\SymfonyBundle\Infrastructure\GraphQl\Type\:
        resource: '../../Infrastructure/GraphQl/Type/*Type.php'
        tags: [ 'overblog_graphql.type' ]

    Xm\SymfonyBundle\Infrastructure\GraphQl\Resolver\:
        resource: '../../Infrastructure/GraphQl/Resolver/*/*Resolver.php'
        tags: [ 'overblog_graphql.resolver' ]

    Xm\SymfonyBundle\Infrastructure\GraphQl\Mutation\:
        resource: '../../Infrastructure/GraphQl/Mutation/*/*Mutation.php'
        tags: [ 'overblog_graphql.mutation' ]
