services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Xm\SymfonyBundle\Command\CreateEventStreamCommand: ~
    Xm\SymfonyBundle\Command\GraphQlDumpSchemaCommand: ~
    Xm\SymfonyBundle\Command\ProjectionRunCommand: ~
    Xm\SymfonyBundle\Command\ProjectionRebuildCommand: ~
    Xm\SymfonyBundle\Command\PurgeCloudflareCacheCommand: ~

    Xm\SymfonyBundle\Messenger\CommandEnricherMiddleware: ~
    Xm\SymfonyBundle\Messenger\CommandRecorderMiddleware: ~
    Xm\SymfonyBundle\Messenger\FailureCatcherMiddleware: ~

    Xm\SymfonyBundle\DataProvider\IssuerProvider: ~

    Xm\SymfonyBundle\EventSourcing\Aggregate\RepositoryFactory: ~

    Xm\SymfonyBundle\EventSourcing\Aggregate\AggregateRepository:
        abstract: true
        factory: ['Xm\SymfonyBundle\EventSourcing\Aggregate\RepositoryFactory', create]

    Xm\SymfonyBundle\EventSourcing\Aggregate\AggregateTranslator: ~
    Xm\SymfonyBundle\EventStore\PersistenceStrategy\StreamStrategy: ~

    Xm\SymfonyBundle\EventStore\MetadataIssuedByEnricher:
        tags: [ 'prooph_event_store.metadata_enricher' ]

    Xm\SymfonyBundle\EventStore\MetadataCausationEnricher:
        tags: [ 'prooph_event_store.metadata_enricher' ]

    Xm\SymfonyBundle\Maker\AggregateRootMaker: ~
    Xm\SymfonyBundle\Maker\ProjectionMaker: ~
