services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Xm\SymfonyBundle\Command\CreateEventStreamCommand: ~
    Xm\SymfonyBundle\Command\GraphQlDumpSchemaCommand: ~
    Xm\SymfonyBundle\Command\ProjectionRunCommand: ~
    Xm\SymfonyBundle\Command\ProjectionDeleteCommand:
        arguments:
            $projectionManager: '@prooph_event_store.projection_manager.app'
    Xm\SymfonyBundle\Command\ProjectionRebuildCommand: ~
    Xm\SymfonyBundle\Command\PurgeCloudflareCacheCommand: ~

    Xm\SymfonyBundle\Messenger\CommandEnricherMiddleware: ~
    Xm\SymfonyBundle\Messenger\CommandRecorderMiddleware: ~
    Xm\SymfonyBundle\Messenger\CausationRecorderMiddleware: ~
    Xm\SymfonyBundle\Messenger\FailureCatcherMiddleware: ~

    Xm\SymfonyBundle\DataProvider\IssuerProvider: ~
    Xm\SymfonyBundle\DataProvider\CausationProvider: ~

    Xm\SymfonyBundle\EventSourcing\Aggregate\RepositoryFactory: ~

    Xm\SymfonyBundle\Infrastructure\Service\RequestInfoProvider: ~

    Xm\SymfonyBundle\EventSourcing\Aggregate\AggregateRepository:
        abstract: true
        factory: ['Xm\SymfonyBundle\EventSourcing\Aggregate\RepositoryFactory', create]

    Xm\SymfonyBundle\EventSourcing\Aggregate\AggregateTranslator: ~
    Xm\SymfonyBundle\EventStore\PersistenceStrategy\StreamStrategy: ~

    Xm\SymfonyBundle\EventStore\MetadataIssuedByEnricher:
        tags: [ 'prooph_event_store.metadata_enricher' ]

    Xm\SymfonyBundle\EventStore\MetadataCausationEnricher:
        tags: [ 'prooph_event_store.metadata_enricher' ]

    Xm\SymfonyBundle\EventStore\MetadataUserAgentEnricher:
        tags: [ 'prooph_event_store.metadata_enricher' ]

    Xm\SymfonyBundle\EventStore\MetadataIpAddressEnricher:
        tags: [ 'prooph_event_store.metadata_enricher' ]

    Xm\SymfonyBundle\Maker\AggregateRootMaker: ~
    Xm\SymfonyBundle\Maker\ProjectionMaker: ~

    Xm\SymfonyBundle\Doctrine\PdoProvider: ~

    prooph_event_store:.projection_factory:
        class: Xm\SymfonyBundle\EventSourcing\ProjectionManagerFactory
